openapi: 3.0.3
info:
  title: Prueba tecnica
  version: 1.0.0
tags:
  - name: Coches
    description: Conjunto de llamadas disponibles para el CRUD de coches
  - name: Extras
    description: Conjunto de llamadas disponibles para el CRUD de extras
  - name: Marcas
    description: Conjunto de llamadas disponibles para el CRUD de marcas
  - name: Precios
    description: Conjunto de llamadas disponibles para el CRUD de precios
paths:
  /coches:
    get:
      tags:
        - Coches
      summary: Recupera todos los coches disponibles
      description: Recupera todos los coches disponibles en el sistema
      operationId: findAllCoches
      security:
        - basicAuth: []
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CocheResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    post:
      tags:
        - Coches
      summary: Inserta un coche en el sistema
      description: Inserta un coche en el sistema, el id no es necesario informarlo ya que se genera automaticamente por la app. Es importante indicar el menos el ´id´ de la marca que tiene el coche, para relacionarlo.
      operationId: insertCoche
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CocheRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CocheResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    put:
      tags:
        - Coches
      summary: Actualiza un coche en el sistema
      description: Actualiza un coche en el sistema, si no encuentra un coche a actualizar, devolvera un NOT FOUND
      operationId: updateCoche
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CocheRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CocheResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /coches/{id}:
    delete:
      tags:
        - Coches
      summary: Borra un coche en el sistema
      description: Borra un coche en el sistema, si no encuentra un coche a borrar, devolvera un NOT FOUND
      operationId: deleteCoche
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: id del coche a borrar
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operacion con exito
        '400':
          description: Id del coche no valido
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /extras:
    get:
      tags:
        - Extras
      summary: Recupera todos los extras disponibles
      description: Recupera todos los extras disponibles en el sistema
      operationId: findAllExtras
      security:
        - basicAuth: []
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExtraResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    post:
      tags:
        - Extras
      summary: Inserta un extra en el sistema
      description: Inserta un extra en el sistema, el id no es necesario informarlo ya que se genera automaticamente por la app. Es importante indicar el menos el ´id´ del coche, para relacionarlo.
      operationId: insertExtra
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtraRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtraResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    put:
      tags:
        - Extras
      summary: Actualiza un extra en el sistema
      description: Actualiza un extra en el sistema, si no encuentra un coche a actualizar, devolvera un NOT FOUND
      operationId: updateExtra
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtraRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtraResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /extras/{id}:
    delete:
      tags:
        - Extras
      summary: Borra un extra en el sistema
      description: Borra un extra en el sistema, si no encuentra un coche a borrar, devolvera un NOT FOUND
      operationId: deleteExtra
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: id del extra a borrar
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operacion con exito
        '400':
          description: Id del extra no valido
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /precios:
    get:
      tags:
        - Precios
      summary: Recupera todos los precios disponibles
      description: Recupera todos los precios disponibles en el sistema
      operationId: findAllPrecios
      security:
        - basicAuth: []
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrecioResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    post:
      tags:
        - Precios
      summary: Inserta un precio en el sistema
      description: Inserta un precio en el sistema, el id no es necesario informarlo ya que se genera automaticamente por la app. Es importante indicar el menos el ´id´ del coche, para relacionarlo.
      operationId: insertPrecio
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrecioRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrecioResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    put:
      tags:
        - Precios
      summary: Actualiza un precio en el sistema
      description: Actualiza un precio en el sistema, si no encuentra un precio a borrar, devolvera un NOT FOUND
      operationId: updatePrecio
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrecioRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrecioResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /precios/{id}:
    delete:
      tags:
        - Precios
      summary: Borra un precio en el sistema
      description: Borra un precio en el sistema, si no encuentra un precio a borrar, devolvera un NOT FOUND
      operationId: deletePrecio
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: id del precio a borrar
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operacion con exito
        '400':
          description: Id del precio no valido
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /marcas:
    get:
      tags:
        - Marcas
      summary: Recupera todos los marcas disponibles
      description: Recupera todos los marcas disponibles en el sistema
      operationId: findAllMarcas
      security:
        - basicAuth: []
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarcaResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    post:
      tags:
        - Marcas
      summary: Inserta un marca en el sistema
      description: Inserta un marca en el sistema, el id no es necesario informarlo ya que se genera automaticamente por la app.
      operationId: insertMarca
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarcaRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarcaResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          description: Internal server error
    put:
      tags:
        - Marcas
      summary: Actualiza un marca en el sistema
      description: Actualiza un marca en el sistema, si no encuentra una marca a actualizar, devolvera un NOT FOUND
      operationId: updateMarca
      security:
        - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MarcaRequest'
      responses:
        '200':
          description: Operacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarcaResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /marcas/{id}:
    delete:
      tags:
        - Marcas
      summary: Borra un marca en el sistema
      description: Borra un marca en el sistema, si no encuentra una marca a borrar, devolvera un NOT FOUND
      operationId: deleteMarca
      security:
        - basicAuth: []
      parameters:
        - name: id
          in: path
          description: id del marca a borrar
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Operacion con exito
        '400':
          description: Id del marca no valido
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Not found
        '500':
          description: Internal server error
components:
  schemas:
    PrecioRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        precio:
          type: number
          format : float
        coche:
          $ref: '#/components/schemas/CocheRequest'
    PrecioResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        precio:
          type: number
          format : float
    MarcaRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
    MarcaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        coches:
          type: array
          items:
            $ref: '#/components/schemas/CocheResponse'
    ExtraRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        coche:
          $ref: '#/components/schemas/CocheRequest'
    ExtraResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
    CocheRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
        modelo:
          type: string
        color:
          type: string
        cilindrada:
          type: integer
          format: int32
        potencia:
          type: integer
          format: int32
        marca:
          $ref: '#/components/schemas/MarcaRequest'
    CocheResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        modelo:
          type: string
        color:
          type: string
        cilindrada:
          type: integer
          format: int32
        potencia:
          type: integer
          format: int32
        extras:
          type: string
        precios:
          type: array
          items:
            $ref: '#/components/schemas/PrecioResponse'
        marca:
          $ref: '#/components/schemas/MarcaResponse'
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Autenticacion incorrecta
      headers:
        WWW_Authenticate:
          schema:
            type: string
